category = "handling"
slug = "data-deletion"
text = "Does the service allow you to permanently delete your personal data?"
notes = ["Even if there is a reasonable delay before the data is fully deleted (as is common), the data still counts as \"permanently deleted\" and satisfies the parameters for this question."]
points = 5

[[options]]
id = "no"
text = "No"
percent = 0

[[options]]
id = "yes-contact"
text = "Yes, by contacting someone"
percent = 60

[[options]]
id = "yes-automated"
text = "Yes, using an automated mechanism"
percent = 100

[[options]]
id = "na"
text = "N/A"
description = "The service doesn't collect any personal information."
percent = 100
