name = "1Password"
description = "1Password is a privacy-focused password manager developed by AgileBits Inc."
slug = "1password"
hostnames = [ "1password.com" ]
sources = [ "https://1password.com/legal/privacy/" ]
icon = "1password.png"
updates = [ ]
contributors = [ ]

[rubric.behavioral-marketing]
value = "no"
citations = [
  "\"We use your personal data to provide you with services associated with the use of 1Password account and to provide you with a rich customer experience through our customer support. In particular, we use your data to provide 1Password services, which includes updating, securing and troubleshooting, and providing support.\""
]

[rubric.security]
value = "yes-independent-audits"
citations = [
  "\"We understand and accept our responsibility to protect Service Data and Secure Data. We use strict access control mechanisms, network isolation, and encryption to ensure that Secure and Service Data is only available to authorized personnel. Additionally, Secure Data cannot be decrypted even by those who do have access to it.\""
]
notes = [
  "PrivacySpy publishes its audits [here](https://support.1password.com/security-assessments/), and while it does not release the results publicly, it is SOC 2 type 2 certified."
]

[rubric.third-party-collection]
value = "no"
citations = [ "\"We do not collect or obtain data from third parties.\"" ]

[rubric.history]
value = "yes"
notes = [
  "Previous versions of the policy are available on 1Password's website."
]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "\"We want happy customers, not trapped ones. We will not lock you out of your own data. However, we are unable to decrypt your Secure Data; you will need your Master Password and Secret Key to decrypt it.\"\r\n\r\n\"You may export your 1Password data at any time you wish during the life of your account. If you discontinue payment, your account will enter a frozen (read-only) state for a period not less than six months during which you may still retrieve and export your data.\"\r\n\r\n\"As we are merely custodians of your data, account owners have the right to instruct us to remove data permanently from our systems. To ensure that no oneâ€™s data is deleted without their consent, you must first delete your account through an authenticated session. **After your account has been deleted, the account owner may contact us and ask for the data to be expunged.** Once the request is authenticated, the data will be removed from our active systems within 72 hours.\""
]

[rubric.data-breaches]
value = "eventually"
citations = [
  "\"In an event of a breach, we recognize our responsibility to our customers and to the public to disclose the nature of the risk and provide a transparent account of the events without undue delay. We follow applicable requirements under the laws, that is, the Canadian data privacy breach notification requirements and the requirements related to data breach notification under the GDPR.\""
]

[rubric.third-party-access]
value = "yes-unspecified-critical"
citations = [
  "\"Your Secure and Service data are held by third party data processors, who provide us with hosting and other infrastructure services. The locations of these are described above. In many cases (but we cannot promise that this will always be the case) even Service data held by these entities is encrypted with keys held only by us.\"\r\n\r\n\"Data needed to process payments is collected by our payment processor, Stripe, Inc., which conforms to the U.S.-E.U. Privacy Shield Framework.\""
]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "\"We retain only enough Service Data to operate and maintain the services. These data are never used for any other purpose.\""
]

[rubric.noncritical-purposes]
value = "opt-out-all"
citations = [
  "The only non-critical data collected is Diagnostic Data. \"This information is sent to us only on a case by case basis, or by users who explicitly opt into our beta software programs or who otherwise explicitly choose to provide diagnostic data to us.\""
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "\"We will comply with applicable laws and the contracts with our customers to provide Service Data and encrypted Secure Data to law enforcement agencies. If permitted, we will notify you of such a request and whether or not we have complied.\""
]

[rubric.list-collected]
value = "generally"
citations = [
  "\"We get some limited data from your use of the 1Password products and services. Such data includes your IP address, and the make and model of your device through which you access or use 1Password products or services.\"\r\n\r\n\"It is visible to our staff and includes, but is not limited to, server logs, billing information, client IP addresses, number of vaults and number of items in vaults, company or family name, and email addresses. Service data includes the name you provide us for your profile and any image that you may upload, at your option and discretion, as part of your profile.\""
]

[rubric.revision-notify]
value = "yes"
citations = [
  "\"At our discretion, we may make changes to this Policy and note the date of the last revision. You should check here frequently if you need to know of updates to our Privacy Policy. We maintain the right to send you annoying email informing you of substantive changes. Previous versions will be made available from this page.\""
]
