name = "2ndLine"
description = 'A "virtual phone" service that provides you with a second phone number for free.'
slug = "2ndline"
hostnames = [ "2ndline.co" ]
sources = [ "2ndline.co/privacy" ]
contributors = [ "mrhedgehog0" ]

[rubric.behavioral-marketing]
value = "yes"
citations = [
  "We may use automated systems to analyze your information to provide you with personalized services and personalized advertisements.\n\nTextNow provides “Free” Services as well as paid Services for users. In order to pay for the “Free” Service, personalized advertisements are placed before you. Your information is used to personalize the advertisements."
]

[rubric.security]
value = "somewhat"
citations = [
  "We safeguard your information in accordance with industry procedures and security standards. HOWEVER, “PERFECT SECURITY” DOES NOT EXIST ON THE INTERNET, THEREFORE, TEXTNOW MAKES NO REPRESENTATIONS OR WARRANTIES WITH REGARD TO THE SUFFICIENCY OF THESE SECURITY MEASURES. TEXTNOW SHALL NOT BE RESPONSIBLE FOR ANY ACTUAL OR CONSEQUENTIAL DAMAGES (OR ANY OTHER DAMAGES OR LIABILITY OF ANY KIND WHATSOEVER, WHETHER AS A RESULT OF NEGLIGENCE OR OTHERWISE) THAT RESULT FROM A LAPSE IN COMPLIANCE WITH THIS PRIVACY POLICY BECAUSE OF A SECURITY BREACH OR TECHNICAL MALFUNCTION."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "5. Third Parties: We may make third party applications, such as extensions, available through the Services. The information collected by us when you enable a third party application is processed under this Privacy Policy. Information collected by the third party application provider is governed by their privacy policies."
]
notes = [
  "The policy doesn't specify what data is collected from 3rd-parties."
]

[rubric.history]
value = "last-modified"
notes = [ "The last modified date is listed at the top of the page." ]

[rubric.data-deletion]
value = "no"
citations = [
  "You may withdraw your consent to the ongoing uses of your information set out in this Privacy Policy at any time, subject to legal or contractual restrictions and reasonable notice. You can withdraw your consent by deactivating your account or by uninstalling the TextNow Application using the standard uninstall procedures that may be available as part of your mobile device or via the mobile application marketplace or network where you obtained the TextNow Application."
]
notes = [
  "The policy says you may deactivate your account, but does not speficy whether your data is ever deleted."
]

[rubric.data-breaches]
value = "no"
notes = [ "No listing was found for this section." ]

[rubric.third-party-access]
value = "yes-specified-noncritical"
citations = [
  "Cookies and Analytical Tracking: Sometimes we use cookie technology, web beacons and other similar devices on our Websites and our software to enhance functionality and navigation, and portions of our Websites and our software may use statistical tools that may be operated by third party providers (collectively, the “Analytical Tools”). The third party providers of Analytical Tools may also transfer this information to other third parties where they are required to do so by law, or where such third parties process the information on their behalf. You consent to the processing of data about you by third party providers of Analytical Tools in the manner and for the purposes set out herein.\n\nWe provide the information we collect to third parties, such as advertisers, in order to provide you with commercial advertisements. An anonymization or pseudonymization (such as hashing) of your email address may be provided to the third parties for these purposes. The provision of such information generate revenue to pay in part or in whole for the Services. We do not provide personal information to third parties except for billing purposes. \n"
]

[rubric.data-collection-reasoning]
value = "mostly"
citations = [
  "1. We use your information to communicate with you, to ensure our services are working as intended, to make improvements to our services, to develop our business, and to protect against fraud and spam.\n\n2. As a provider of telecommunications services, we are subject to legal and regulatory requirements to retain some of your information such as telephone toll records for a period of time.\n\n3. We provide the information we collect to third parties, such as advertisers, in order to provide you with commercial advertisements. An anonymization or pseudonymization (such as hashing) of your email address may be provided to the third parties for these purposes. The provision of such information generate revenue to pay in part or in whole for the Services. We do not provide personal information to third parties except for billing purposes.\nIf you would like more information about this practice and to know your choices about not having this information used by these companies, click here (http://www.networkadvertising.org/managing/opt_out.asp)[http://www.networkadvertising.org/managing/opt_out.asp].\n\n4. We may use different technologies to process your information for these purposes. We may use automated systems to analyze your information to provide you with personalized services and personalized advertisements. And we may analyze your information to help us detect abuse such as spam, malware, and illegal content.\n\n5. Our advertising partners may place or recognize a cookie on your computer or device, and may use a de-identified, non-human readable version of your email address for matching to other data collected from (or across) sites about you to improve the relevance of online advertising and personalization. Never is your actual email address shared with any company. To learn more about interest-based advertising in general and to opt out, please visit (http://www.aboutads.info/choices)[http://www.aboutads.info/choices]."
]

[rubric.noncritical-purposes]
value = "no"
notes = [
  "The policy does not mention opting out of non-critical data collection."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "Our servers are located in the United States and Canada. Accordingly, in connection with providing you with the Services, your information will be processed and stored in the United States and Canada. The governments, courts, law enforcement, and regulatory agencies of which are able to obtain disclosure of your information through the laws of the United States or the laws of Canada."
]

[rubric.list-collected]
value = "generally"
citations = [
  "1. Personal Information: When you sign up for a user account for any of the Services, We collect personal information, such as your name, and email address. When you sign up for paid service, we also collect your payment information for billing purposes.\n\n2. Device Information: When you access our website or use our software, (TextNow Application and/or 2ndline Application), the information we collect include IP Addresses, location data, Device ID, Advertiser ID, browser type and settings, device type and settings, and operating system (such as iOS and Android).\n\n3. Cookies and Analytical Tracking: Sometimes we use cookie technology, web beacons and other similar devices on our Websites and our software to enhance functionality and navigation, and portions of our Websites and our software may use statistical tools that may be operated by third party providers (collectively, the “Analytical Tools”). The third party providers of Analytical Tools may also transfer this information to other third parties where they are required to do so by law, or where such third parties process the information on their behalf. You consent to the processing of data about you by third party providers of Analytical Tools in the manner and for the purposes set out herein.\n\n4. User communications: When you use our Services to make and receive telephone calls or send and receive messages (including voice and text messages, video, and pictures), we are required to collect telephony log information (telephone toll records) like your calling-party number, receiving-party number, forwarding numbers, time and date of calls and messages, duration of calls, routing information, and types of calls. Your messages are also collected.\n\n5. Third Parties: We may make third party applications, such as extensions, available through the Services. The information collected by us when you enable a third party application is processed under this Privacy Policy. Information collected by the third party application provider is governed by their privacy policies. For example:\n(Emoji Privacy Policy)[https://www.emoji.com/privacy-policy]\n\n6. We “do not track” you across third party websites. However, we do track you as per this Privacy Policy, and further some of our third party advertisers may also track you across other websites or online services."
]

[rubric.revision-notify]
value = "yes"
citations = [
  "Notification of any major changes may be sent to you by email or a system message to your account."
]
