name = "Any.do"
description = "Any.do is a productivity platform based in Tel Aviv and San Francisco."
slug = "any-do"
hostnames = [ "any.do", "support.any.do", "blog.any.do" ]
sources = [ "https://www.any.do/legal/privacy-policy" ]
contributors = [ "doamatto" ]

[rubric.behavioral-marketing]
value = "yes-opt-in"
citations = [
  "In addition to the recipients described in Section 1, we may share your information as follows: [...] Where you have provided your consent to us sharing the Personal Data (e.g., where you provide us with marketing consents or opt-in to optional additional services or functionality); and"
]

[rubric.security]
value = "somewhat"
citations = [
  "We have implemented appropriate technical, organizational and security measures designed to reduce the risk of accidental destruction or loss, or the unauthorized disclosure or access to such information appropriate to the nature of the information concerned. However, please note that we cannot guarantee that the information will not be exposed as a result of unauthorized penetration to our servers. As the security of information depends in part on the security of the computer, device or network you use to communicate with us and the security you use to protect your user IDs and passwords, please make sure to take appropriate measures to protect this information."
]

[rubric.third-party-collection]
value = "no"
notes = [ "Data is not collected by third-parties." ]

[rubric.history]
value = "no"
notes = [ "There is no date or changelog to be found" ]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "Should you ever decide to delete your Account, you may do so by emailing privacy@any.do. If you terminate your Account, any association between your Account and information we store will no longer be accessible through your Account. However, given the nature of sharing on the Services, any public activity on your Account prior to deletion will remain stored on our servers and will remain accessible to the public."
]

[rubric.data-breaches]
value = "no"
notes = [ "The service is not required to notify you of data breaches" ]

[rubric.third-party-access]
value = "yes-specified-critical"
citations = [
  "When you create an account and make use of our services as a registered user:\n\nData we collect: Facebook Id / Google Id / Email; Full name; Location; Hashed password; Analytics events (how the product is being used).\n[...]\n3rd party platforms such as for the following purposes: Hosting; Vendors.\n\n[...]\n\nWhen you contact us [...]:\n\nData we collect: Full name; Email address; Location; Device type; Version of the product being used; OS version being used; Any other information that you decide to provide/supply us.\n[...]\n3rd party platforms such as for the following purposes: Customer support services.\n\n[...]\n\nWhen we process your job application:\n\nData we collect: Full name; Email address; Phone number; Work history; Education; Resume; Any other information that you decide to provide/supply us.\n[...]\n3rd party platforms such as for the following purposes: HR solution provider.\n\n[...]\n\nIn addition to the recipients described in Section 1, we may share your information as follows: To the extent necessary, with regulators, to comply with all applicable laws, regulations and rules, and requests of law enforcement, regulatory and other governmental agencies or if required to do so by court order; If, in the future, we sell or transfer some or all of our business or assets to a third party, we will (to the minimum extent required) disclose information to a potential or actual third party purchaser of our business or assets. In the event that we are acquired by or merged with a third party entity, or in the event of bankruptcy or a comparable event, we reserve the right to transfer or assign Personal Data in connection with the foregoing events; Where you have provided your consent to us sharing the Personal Data (e.g., where you provide us with marketing consents or opt-in to optional additional services or functionality); and: Where we receive requests for information from law enforcement or regulators, we carefully validate these requests before any Personal Data is disclosed.\n[...]\nThe Product may enable you to interact with or contain links to your Third Party Account and other third party websites, mobile software applications and services that are not owned or controlled by us (each a “Third Party Service”). We are not responsible for the privacy practices or the content of such Third Party Services. Please be aware that Third Party Services may collect Personal Information from you. Accordingly, we encourage you to read the terms and conditions and privacy policy of each Third Party Service that you choose to use or interact with."
]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "Why we collect this data: Creating an account; To personalize the services; Processing the order of the Service; Performing/executing the Service[;]\n[...]\nTo provide our service and certain features of the product;\nTo improve our product and quality of service[;]\n[...]\nTo assist you;\nTo respond your query[;]\n[...]\nProcess your job application;\nTo assess the candidate."
]

[rubric.noncritical-purposes]
value = "opt-out-all"
citations = [
  "In addition to the recipients described in Section 1, we may share your information as follows: [...] Where you have provided your consent to us sharing the Personal Data (e.g., where you provide us with marketing consents or opt-in to optional additional services or functionality); and[.]"
]

[rubric.law-enforcement]
value = "always"
citations = [
  "To the extent necessary, with regulators, to comply with all applicable laws, regulations and rules, and requests of law enforcement, regulatory and other governmental agencies or if required to do so by court order;"
]

[rubric.list-collected]
value = "exhaustively"
citations = [
  "When you create an account and make use of our services as a registered user:\nData we collect: Facebook Id / Google Id / Email; Full name; Location; Hashed password; Analytics events (how the product is being used).\n[...]\n\nWhen you contact us [...]:\nData we collect: Full name; Email address; Location; Device type; Version of the product being used; OS version being used; Any other information that you decide to provide/supply us.\n[...]\n\nWhen we process your job application:\nData we collect: Full name; Email address; Phone number; Work history; Education; Resume; Any other information that you decide to provide/supply us."
]

[rubric.revision-notify]
value = "yes"
citations = [
  "This Privacy Policy may be updated from time to time and therefore we ask you to check back periodically for the latest version of the Privacy Policy, as indicated below. If there will be any significant changes made to the use of your Personal Data in a manner different from that stated at the time of collection, we will notify you by posting a notice on our Website or by other means."
]
