name = "Discord"
description = 'Discord is a chatting service for gamers, featuring VoIP calling and chat communities divided into "servers".'
slug = "discord"
hostnames = [ "discordapp.com" ]
sources = [ "https://discordapp.com/privacy" ]
icon = "discord.png"
updates = [ ]
contributors = [ "nep" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  "The Company and its affiliates may use this information to contact you in the future to tell you about services we believe will be of interest to you.\r\n\r\n[...]\r\n\r\nYou may see our Service advertised in other applications or websites. After clicking on one of these advertisements and installing our Service, you will become a user of the Service. **Advertising platforms, which include Twitter and Facebook (and whose SDKs are integrated within our Service), may collect information for optimizing advertising campaigns outside of the Service.**\r\n\r\nIf you do not wish to receive personalized advertising that is delivered by third parties outside of the Discord Service, you may be able to exercise that choice through opt-out programs that are administered by third parties, including the Network Advertising Initiative (NAI), the Digital Advertising Alliance (DAA). Our Services currently do not respond to “Do Not Track” (DNT) signals and operate as described in this Privacy Policy whether or not a DNT signal is received, as there is no consistent industry standard for compliance."
]

[rubric.security]
value = "no"
citations = [
  "We take reasonable steps to protect the information provided via the Services from loss, misuse, and unauthorized access, disclosure, alteration, or destruction. However, no Internet or email transmission is ever fully secure or error free. In particular, email sent to or from the Services may not be secure. Therefore, you should take special care in deciding what information you send to us via email. Please keep this in mind when disclosing any information via the Internet."
]
notes = [ "\"Reasonable Steps\" is the only information given." ]

[rubric.third-party-collection]
value = "yes"
citations = [
  "You may give us permission to collect your information in other services. For example, you may connect a social networking service (\"SNS\") such as Facebook or Twitter to your Discord account. When you do this, it allows us to obtain information from those accounts (for example, your friends or contacts)."
]
notes = [
  "The policy does not specify that this information can only be used for core service functions."
]

[rubric.history]
value = "yes"
notes = [
  "Discord provides both a last modified date as well as copies of previous policies."
]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "In addition to the functionality available through the “Settings” of the Services, in which you can correct, update, amend, or delete certain personal data, you can also request other modifications from us directly.\r\n\r\n[...]\r\n\r\nPlease write us at privacy@discordapp.com with the words “Personal Data Request” in the subject or body of your message, along with an explanation of what data subject right you are seeking to exercise. For your protection, we may take steps to verify identity before responding to your request."
]
notes = [
  "When deleting an account, or in the case your account was suspended, Discord still retains some data such as your IP address (this can be proven by joining a server, deleting your account, waiting 14 days, and trying to join on a new account)."
]

[rubric.data-breaches]
value = "no"
notes = [ "The policy doesn't specify a data breach protocol." ]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "Business Transfers: As we develop our business, we might sell or buy businesses or assets. In the event of a corporate sale, merger, reorganization, bankruptcy, dissolution or similar event, your information may be part of the transferred assets.\r\n\r\nConsent: We may transfer your information with your consent.\r\n\r\nRelated Companies: We may also share your information with our Related Companies for purposes consistent with this Privacy Policy.\r\n\r\nDevelopers: Developers using our SDK or API will have access to their end users’ information, including message content, message metadata, and voice metadata. Developers must use such information only to provide the SDK/API functionality within their applications and/or services.\r\n\r\nAgents, Consultants and Related Third Parties: Like many businesses, we sometimes hire other companies or individuals to perform certain business-related functions. Examples of such functions include mailing information, maintaining databases and processing payments.\r\n\r\nLegal Requirements: We may disclose your information if required to do so by law or in the good faith belief that such action is necessary to (i) comply with a legal obligation, (ii) protect and defend the rights or property of the Company or Related Companies, (iii) protect the personal safety of users of the Services or the public, or (iv) protect against legal liability.\r\n\r\nAggregated or Non-identifiable Data: We may also share aggregated or non-personally identifiable information with our partners or others for business purposes.\r\n\r\nAfter clicking on one of these advertisements and installing our Service, you will become a user of the Service. Advertising platforms, which include Twitter and Facebook (and whose SDKs are integrated within our Service), may collect information for optimizing advertising campaigns outside of the Service."
]

[rubric.data-collection-reasoning]
value = "mostly"
citations = [
  "[If] you provide information in order to obtain access to the Services, we will use your information to provide you with access to such services and to monitor your use of such services [...]\r\n\r\nFor example, we handle personal data on this basis to create your account and provide our Services.\r\n\r\n[...]\r\n\r\nIn many cases, we handle personal data on the ground that it furthers our legitimate interests in ways that are not overridden by the interests or fundamental rights and freedoms of the affected individuals: This includes:\r\n\r\nProviding a safe and enjoyable user experience;\r\n\r\nCustomer service;\r\n\r\nMarketing, e.g. sending emails or other communications to let you know about new features;\r\n\r\nProtecting our users, personnel, and property;\r\n\r\nAnalyzing and improving our business, e.g. collecting information about how you use our Services to optimize the design and placement of certain features;\r\n\r\nProcessing job applications;\r\n\r\nManaging legal issues.\r\n\r\n[...]\r\n\r\nWe need to use and disclose personal data in certain ways to comply with our legal obligations.\r\n\r\n[...]\r\n\r\nWe may collect or share personal data to help resolve an urgent medical situation.\r\n\r\n[...]\r\n\r\nWhere required by law, and in some other cases, we handle personal data on the basis of your implied or express consent."
]
notes = [
  "Due to the use of phrases like \"such as,\" the list of uses for collected data—while long—cannot be considered exhaustive or binding."
]

[rubric.noncritical-purposes]
value = "opt-out-all"
citations = [
  "Discord offers you the ability to restrict the processing of your data for specific uses, which you can find in the “Settings” page of the services. Individuals in the European Economic Area have the right to opt out of all of our processing of their personal data for direct marketing purposes. To exercise this right, please see the “Settings” page for your Account. You may also click the “unsubscribe” link in any of our marketing emails.\r\n\r\nIn addition to the functionality available through the “Settings” of the Services, in which you can correct, update, amend, or delete certain personal data, you can also request other modifications from us directly. Please write us at privacy@discordapp.com with the words “Personal Data Request” in the subject or body of your message, along with an explanation of what data subject right you are seeking to exercise. For your protection, we may take steps to verify identity before responding to your request."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "We may disclose your information if required to do so by law or in the good faith belief that such action is necessary to (i) comply with a legal obligation, (ii) protect and defend the rights or property of the Company or Related Companies, (iii) protect the personal safety of users of the Services or the public, or (iv) protect against legal liability."
]

[rubric.list-collected]
value = "generally"
citations = [
  "Information You Provide: We collect information from you when you voluntarily provide such information, such as when you register for access to the Services or use certain Services. Information we collect may include but not be limited to username, email address, and any messages, images, transient VOIP data (to enable communication delivery only) or other content you send via the chat feature.\r\n\r\n[...]\r\n\r\nWe collect the following categories of personal information: identifiers (such as your username, the email address you use to sign up, and your phone number, if you’ve chosen to provide it); commercial information (a record of what you’ve bought from Discord, if anything); financial data (payment information, if you’ve bought anything from Discord); internet or other network information (how you interact with the application); location information (because your IP address may indicate your general location); inference data about you; and other information that identifies or can be reasonably associated with you. For examples of the precise data points we collect and the sources of such collection, please see the “INFORMATION WE COLLECT” section above. We collect personal information for the business and commercial purposes described in “OUR USE OF YOUR INFORMATION” above."
]

[rubric.revision-notify]
value = "no"
citations = [
  "We reserve the right to update or modify this Privacy Policy at any time and from time to time without prior notice. Please review this policy periodically, and especially before you provide any information"
]
