name = "Facebook"
description = "Facebook, Inc. is the world's largest online social network and has undergone several privacy scandals."
slug = "facebook"
hostnames = [ "facebook.com" ]
sources = [ "https://www.facebook.com/privacy/explanation" ]
icon = "facebook.png"
contributors = [ "ibarakaiev", "milesmcc" ]

[rubric.behavioral-marketing]
value = "yes"
citations = [
  "\"To create personalized Products that are unique and relevant to you, we use your connections, preferences, interests and activities based on the data we collect and learn from you and others (including any data with special protections you choose to provide); how you use and interact with our Products; and the people, places, or things you're connected to and interested in on and off our Products.\""
]

[rubric.security]
value = "no"
notes = [
  "The policy does not mention the steps Facebook takes to secure its data."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "\"Advertisers, app developers, and publishers can send us information through Facebook Business Tools they use, including our social plug-ins (such as the Like button), Facebook Login, our APIs and SDKs, or the Facebook pixel. These partners provide information about your activities off Facebook—including information about your device, websites you visit, purchases you make, the ads you see, and how you use their services—whether or not you have a Facebook account or are logged into Facebook. For example, a game developer could use our API to tell us what games you play, or a business could tell us about a purchase you made in its store. We also receive information about your online and offline actions and purchases from third-party data providers who have the rights to provide us with your information.\""
]

[rubric.history]
value = "last-modified"
notes = [
  "The policy includes a 'date of last revision' on the bottom of the policy, but does not have a change-log or revision history."
]

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "We provide you with the ability to access, rectify, port and erase your data."
]

[rubric.data-breaches]
value = "no"
notes = [ "No part of the policy specifies a data breach protocol." ]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "\"We work with third-party partners who help us provide and improve our Products or who use Facebook Business Tools to grow their businesses, which makes it possible to operate our companies and provide free services to people around the world. We don't sell any of your information to anyone, and we never will. We also impose strict restrictions on how our partners can use and disclose the data we provide.\""
]

[rubric.data-collection-reasoning]
value = "somewhat"
citations = [
  "\"Information across Facebook Products and devices: We connect information about your activities on different Facebook Products and devices to provide a more tailored and consistent experience on all Facebook Products you use, wherever you use them. For example, we can suggest that you join a group on Facebook that includes people you follow on Instagram or communicate with using Messenger. We can also make your experience more seamless, for example, by automatically filling in your registration information (such as your phone number) from one Facebook Product when you sign up for an account on a different Product.\""
]

[rubric.noncritical-purposes]
value = "opt-out-some"
notes = [ "Available in \"settings\" on the website." ]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "\"In response to a legal request (like a search warrant, court order or subpoena) if we have a good faith belief that the law requires us to do so. This may include responding to legal requests from jurisdictions outside of the United States when we have a good-faith belief that the response is required by law in that jurisdiction, affects users in that jurisdiction, and is consistent with internationally recognized standards.\""
]

[rubric.list-collected]
value = "generally"
citations = [
  "\"Device operations: information about operations and behaviors performed on the device, such as whether a window is foregrounded or backgrounded, or mouse movements (which can help distinguish humans from bots).\"\r\n\r\n\"Identifiers: unique identifiers, device IDs, and other identifiers, such as from games, apps or accounts you use, and Family Device IDs (or other identifiers unique to Facebook Company Products associated with the same device or account).\""
]

[rubric.revision-notify]
value = "yes"
citations = [
  "\"We'll notify you before we make changes to this policy and give you the opportunity to review the revised policy before you choose to continue using our Products.\""
]

[[updates]]
title = "Exposed Phone Numbers"
description = "In the latest privacy scandal for the tech giant, hundreds of millions of phone numbers linked to Facebook accounts were exposed on a server without authentication. Some of the records also included personal information such as the user's name, gender, and country."
date = "2019-09-05T13:00:55.983593+00:00"
sources = [ "https://techcrunch.com/2019/09/04/facebook-phone-numbers-exposed/" ]

[[updates]]
title = "Data Breach"
description = "More than 540 million records about Facebook users were publicly exposed on Amazon's cloud computing service, according to a cybersecurity research firm."
date = "2019-08-28T13:35:35.375727+00:00"
sources = [ "https://www.cbsnews.com/news/millions-facebook-user-records-exposed-amazon-cloud-server/" ]
