name = "Fur Affinity"
description = "The largest and most popular anthropomorphic art website on the net."
slug = "fur-affinity"
hostnames = [ "https://www.furaffinity.net" ]
sources = [ "https://www.furaffinity.net/privacy" ]
contributors = [ "Donno" ]

[rubric.behavioral-marketing]
value = "yes"
citations = [
  "Cookies and Tracking\nFur Affinity tracks users over time and over our Furaffinity subdomain websites. We record users' use of the Site, comments they make and the pages that they visit. Third party providers of external services that provide advertising, such as DoubleClick by Google, may track users over time and over our Site and third party apps or websites and such third parties may also place cookies, via our Site. You can read more about privacy and cookies set by DoubleClick by Google"
]

[rubric.security]
value = "somewhat"
citations = [
  "Security\nWe may employ procedural and technological measures, consistent with industry practice. Such measures are reasonably designed to help protect your personally identifiable information from loss, unauthorized access, disclosure, alteration or destruction. Fur Affinity may use encryption, secure socket layer, password protection and other internal measures to help prevent unauthorized access to your personally identifiable information. We also have internal policies for the safe handling of data. We will endeavor to destroy your information when we no longer have a legitimate business need to use it, except for backups that are archived and retained in the ordinary course of business."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "Third party providers of external services that provide advertising, such as DoubleClick by Google, may track users over time and over our Site and third party apps or websites and such third parties may also place cookies, via our Site."
]

[rubric.history]
value = "last-modified"
citations = [ "Updated - 12/26/2019 " ]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "You have a right request deletion\nYou have a right to request that Fur Affinity delete your personal data that it holds. This isn't an automatic right, and what Fur Affinity is able to delete will depend on the type of data that we hold about you, whether it was obtained via consent, what purpose it serves, and whether Fur Affinity has an obligation to keep the data, among other things.\n\nNote that unless you request deletion, and such request is determined to be appropriate, while you remain a user, we'll process and retain your data as described in this Privacy Notice in order to enable you to use the Services. Once you stop being a user, we will hold your data as described in the data retention section.\n\nRequests for deletions can be sent to deleteme@furaffinity.net."
]

[rubric.data-breaches]
value = "no"
citations = [ "The policy doesn't specify a data breach protocol." ]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "Disclosure\nWe may provide your personally identifiable information and the data generated by cookies and the aggregate information to the vendors and service agencies that we may engage to assist us in providing our services to you for their use solely to provide us with such assistance. We will also disclose your personally identifiable information (a) if we are required to do so by law, regulation or other government authority or otherwise in cooperation with an ongoing investigation of a governmental authority, (b) to enforce the Fur Affinity Terms of Service or user agreements or to protect our rights or (c) to protect the safety of users of our Site and our services. We will not sell your personally identifiable information to any company or organization, but we may transfer your personally identifiable information to a successor entity upon a merger, consolidation or other corporate reorganization in which Fur Affinity participates or to a purchaser or acquirer of all or substantially all of Fur Affinity's assets to which the Site relates."
]

[rubric.data-collection-reasoning]
value = "no"
citations = [
  "To register an account at Fur Affinity we request certain personal data from you on the registration form such as your username, password, email address, and date of birth.\nWe also collect the location data, including city, metro code, zip code, state, country, latitude and longitude and area code through your IP address as well as your browser id.\nIn addition, when you register, we may collect any personal data that you personally elect to include in your public profile, including email addresses or contact information."
]

[rubric.noncritical-purposes]
value = "no"
citations = [ "The policy doesn't specify this." ]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "We may provide your personally identifiable information and the data generated by cookies and the aggregate information to the vendors and service agencies that we may engage to assist us in providing our services to you for their use solely to provide us with such assistance. We will also disclose your personally identifiable information (a) if we are required to do so by law, regulation or other government authority or otherwise in cooperation with an ongoing investigation of a governmental authority."
]

[rubric.list-collected]
value = "generally"
citations = [
  "Information Collection and Use\nTo register an account at Fur Affinity we request certain personal data from you on the registration form such as your username, password, email address, and date of birth.\n\nWe also collect the location data, including city, metro code, zip code, state, country, latitude and longitude and area code through your IP address as well as your browser id.\n\nIn addition, when you register, we may collect any personal data that you personally elect to include in your public profile, including email addresses or contact information.\n\nUnless you have set your preferences to hide certain data other users on our service will be able to view your profile data (which includes your username or any customizable data which you may have provided, such as a bio, contact information, or personal preferences).\n"
]

[rubric.revision-notify]
value = "yes"
citations = [
  "Privacy Policy Updates\nFur Affinity may need to update this Privacy Policy from time to time. If so, Fur Affinity will post our updated Privacy Policy on our Site, along with notice that the Privacy Policy has been changed so you are always aware of what personally identifiable information we may collect and how we may use this information. Fur Affinity may also send users a notification notifying such users of any changes to the Privacy Policy. Fur Affinity encourages you to review this Privacy Policy regularly for any changes. Your continued use of the Site and/or continued provision of personally identifiable information to us will be subject to the terms of the then-current Privacy Policy.\n"
]
