name = "GearBest"
description = "GearBest is an online marketplace with a focus on electronics"
slug = "gearbest"
hostnames = [ "gearbest.com" ]
sources = [ "https://www.gearbest.com/about/privacy-policy.html" ]
contributors = [ "vutut" ]

[rubric.behavioral-marketing]
value = "yes"
notes = [
  "Not mentioned in privacy policy, but [cookie policy](https://www.gearbest.com/about/cookie-policy.html) allows for targeted marketing."
]

[rubric.security]
value = "yes-independent-audits"
citations = [
  "Our servers and website are security scanned and fully verified externally by McAfee Secure from Symantec on a daily basis to protect you online."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "We may contract with third-party service providers to assist us in better understanding our site visitors."
]

[rubric.history]
value = "no"
citations = [
  "If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below."
]
notes = [
  "While the policy mentions that it may include a modification date, this is absent."
]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "You have the right to access, correct, or delete the personal information that we collect.\n[...]\nIf you would like to exercise one of your rights as set out above, or if you have a question or a complaint about this policy, the way your personal information is processed, please contact us via e-mail: support@gearbest.com"
]

[rubric.data-breaches]
value = "no"
notes = [ "No provision for dealing with breaches in policy." ]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "We do not sell, trade, or otherwise transfer to outside parties your personal information. This does not include trusted third parties who assist us in operating our website, conducting our business, executing payments, delivering purchased products or services, sending you information or updates or otherwise servicing you, so long as those parties agree to keep this information confidential. "
]

[rubric.data-collection-reasoning]
value = "mostly"
citations = [
  "The information we collect from you may be used in the following ways:\n\n- To personalize your experience\n(your information helps us to better respond to your individual needs)\n- To improve our website and your shopping experience\n(we continually strive to improve our website offerings based on the information and feedback we receive from you)\n- To improve customer service\n(your information helps us to more effectively respond to your customer service requests and support needs)\n- To process transactions including executing your payments and delivering the purchased products or services requested.\n- To administer a contest, special promotion, survey, activity or other site feature.\n- To send periodic emails  \nThe email address you provide for order processing, may be used to send you important information and updates pertaining to your order, in addition to receiving occasional company news, updates, related product or service information, etc.\n- To send periodic SMS messages  \nThe phone number you provide during customer registration and/or order processing, may occasionally be used to send you important marketing and promotional information related to products and services that may be of interest to you."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety."
]

[rubric.list-collected]
value = "summarily"
citations = [
  "When ordering or registering on our site, as appropriate, you may be asked to enter the following information: your name, e-mail address, mailing address and phone number. You may, however, also visit our site anonymously. \n[...]\nWe use the information you provide to us for the specific purposes for which you provide the information, as stated at the time of collection, and as otherwise permitted by law.\n[...]\nWe use cookies to help us remember and process the items in your shopping cart, understand and save your preferences for future visits and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools for you in the future."
]

[rubric.revision-notify]
value = "no"
citations = [
  "If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below."
]
