name = "Gen.xyz"
description = "Gen.xyz is a domain registry."
slug = "gen-xyz"
hostnames = [ "gen.xyz" ]
sources = [ "https://gen.xyz/privacy" ]
contributors = [ "doamatto" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  "We do not track our customers over time and across third party websites, and therefore do not respond to Do Not Track (DNT) signals. However, in addition to using cookies and related technologies as described above, we also may permit certain third party companies to help us tailor advertising that we think may be of interest to users and to collect and use other data about user activities on our Sites and/or Services (e.g., to allow them to tailor ads on third party services). These companies may deliver ads that might also place cookies and otherwise track user behavior across third party websites.\n\nWe use Google Analytics’ 3rd-party audience data such as age, gender and interests to better understanding the behavior of our customers and work with companies that collect information about your online activities to provide advertising targeted to suit your interests and preferences. For example, you may see certain ads on this website or other websites because we contract with Google and other similar companies to target our ads based on information we or they have collected, including information that was collected through automated means (such as cookies and web beacons). These companies also use automated technologies to collect information when you click on our ads, which helps track and manage the effectiveness of our marketing efforts.\n\nYou may opt out of the automated collection of information by third-party ad networks for the purpose of delivering advertisements tailored to your interests, by editing your Google Display Network ads’ preferences at http://www.google.com/ads/preferences/. For further information regarding the privacy practices of our advertisement provider, please visit http://www.google.com/privacypolicy.html."
]

[rubric.security]
value = "somewhat"
citations = [
  "We have implemented measures designed to secure your personal information from accidental loss and from unauthorized access, use, transmission alteration, and disclosure. The safety and security of your information also depends on you. Where we have given you (or where you have chosen) a password for access to certain parts of our website, you are responsible for keeping this password confidential. Unfortunately, the transmission of information via the internet is not completely secure. Although we do our best to protect your personal information, we cannot guarantee the security of your personal information transmitted to our website. Any transmission of personal information is at your own risk."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "We use information gathered about you from our site statistics via log files provided by third party tracking partners (for example your IP address) to help diagnose problems with our server, and to administer our website. We also gather broad demographic information from this data to help us improve our site and your experience. This information collection is not linked to any personally identifiable information. Our site uses cookies to keep track of your session information and to provide you with customized information. We do link the information we store in cookies to personally identifiable information you submit while on our site."
]

[rubric.history]
value = "last-modified"
citations = [ "Last modified: May 17, 2018" ]

[rubric.data-deletion]
value = "no"
notes = [
  "This policy does not require the service to allow you to delete your data"
]

[rubric.data-breaches]
value = "no"
notes = [
  "This policy does not require the service to alert you in the event of a breach"
]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "We may share specific information with business partners or contractors when the information is needed to fulfill your request for a product or service.\n[...]\nWe do not give third parties access to your personal information other than as outlined in this privacy policy. We will never give any information about you to others without your express permission. We may share specific information with business partners or contractors when the information is needed to fulfill your request for a product or service. We also use your contact information when it will be important for us to contact you regarding functionality changes to our products, our website, new services and special offers we think you’ll find valuable and provide customer service. You can contact us at the email address at the bottom of this page if you would like to make any modification to the information you have provided us."
]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "The website uses forms where you give us personal information (like your name, address, phone number, payment information and email address) so you can create an account, place orders, request information, etc. If you do not provide this information, we may not be able to provide you with the services offered on this website."
]

[rubric.noncritical-purposes]
value = "opt-out-some"
citations = [
  "You may opt out of the automated collection of information by third-party ad networks for the purpose of delivering advertisements tailored to your interests, by editing your Google Display Network ads’ preferences at http://www.google.com/ads/preferences/. For further information regarding the privacy practices of our advertisement provider, please visit http://www.google.com/privacypolicy.html."
]

[rubric.law-enforcement]
value = "unspecified"
notes = [
  "It is not mentioned when your data is given to law enforcement."
]

[rubric.list-collected]
value = "summarily"
citations = [
  "The website uses forms where you give us personal information (like your name, address, phone number, payment information and email address) so you can create an account, place orders, request information, etc. If you do not provide this information, we may not be able to provide you with the services offered on this website."
]

[rubric.revision-notify]
value = "no"
citations = [
  "This privacy policy may be revised periodically and this will be reflected by the date above. Please revisit this page to stay aware of any changes. By using the website you agree to the privacy practices disclosed below."
]
