name = "GitHub"
description = "Github is a development platform for sharing and publishing code using Git repositories."
slug = "github"
hostnames = [ "github.com" ]
sources = [
  "https://help.github.com/en/articles/github-privacy-statement"
]
contributors = [ "ftsell", "milesmcc" ]

[rubric.behavioral-marketing]
value = "no"
citations = [
  "We do not host advertising on GitHub and we do not sell your personal information.\r\n\r\nWe use User Personal Information and other data to make recommendations for you, such as to suggest projects you may want to follow or contribute to. For example, when you fill out an interest survey at account creation, we learn from it — as well as from your public behavior on GitHub, such as the projects you star — to determine your coding interests, and we recommend similar projects. These recommendations are automated decisions, but they have no legal impact on your rights."
]
notes = [
  "Suggestions aren't classified as marketing even though it is a method of binding users to the platform and could therefore be argued as a form of self-marketing."
]

[rubric.security]
value = "somewhat"
citations = [
  "GitHub enforces a written security information program. Our program:\r\n\r\n* aligns with industry recognized frameworks;\r\n* includes security safeguards reasonably designed to protect the confidentiality, integrity, availability, and resilience of our users' data;\r\n* is appropriate to the nature, size, and complexity of GitHub’s business operations;\r\n* includes incident response and data breach notification processes;\r\n* complies with applicable information security related laws and regulations in the geographic regions where GitHub does business."
]

[rubric.third-party-collection]
value = "critical-only"
citations = [
  "From time to time, GitHub receives personal information about individuals from third parties. This may happen if you sign up for a training or to receive information about GitHub from one of our vendors."
]

[rubric.history]
value = "yes"
citations = [
  "We will provide notification to Users of material changes to this Privacy Statement through our Website at least 30 days prior to the change taking effect by posting a notice on our home page or sending email to the primary email address specified in your GitHub account. We will also update our Site Policy repository, which tracks all changes to this policy"
]

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "If you're already a GitHub user, you may access, update, alter, or delete your basic user profile information by editing your user profile or contacting GitHub Support or GitHub Premium Support. You can control the information we collect about you by limiting what information is in your profile, by updating out of date information, or by contacting GitHub Support or GitHub Premium Support.\r\n\r\nIf GitHub processes information about you and you do not have an account, such as information GitHub receives from third parties, then you may access, update, alter, delete, or object to the processing of your personal information by contacting GitHub Support or GitHub Premium Support.\r\n\r\nIf you would like to cancel your account or delete your User Personal Information, you may do so in your user profile. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements, but barring legal requirements, we will delete your full profile (within reason) within 90 days. You may contact GitHub Support or GitHub Premium Support to request the erasure of the data we process on the basis of consent within 30 days."
]
notes = [
  "If you are registered, it is an automated process, otherwise you have to contact someone."
]

[rubric.data-breaches]
value = "eventually"
citations = [
  "In the event of a data breach that affects your User Personal Information, we will act promptly to mitigate the impact of a breach and notify any affected users without undue delay."
]

[rubric.third-party-access]
value = "yes-specified-critical"
citations = [
  "We do share User Personal Information with a limited number of third party vendors [...].\r\n\r\nOur vendors perform services such as payment processing, customer support ticketing, network data transmission, and other similar services."
]
notes = [
  "Subprocessors listed at https://help.github.com/en/articles/github-subprocessors-and-cookies"
]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "We need your User Personal Information to create your account, and to provide the services you request, including to provide the GitHub service, the Marketplace service, the Sponsors Program, or to respond to support requests.\r\n\r\nWe use your User Personal Information, specifically your user name, to identify you on GitHub.\r\n\r\nWe use it to fill out your profile and share that profile with other users if you ask us to.\r\n\r\nWe will use your email address to communicate with you, if you've said that's okay, and only for the reasons you’ve said that’s okay. Please see our section on email communication for more information.\r\n\r\nWe use User Personal Information and other data to make recommendations for you, such as to suggest projects you may want to follow or contribute to. For example, when you fill out an interest survey at account creation, we learn from it — as well as from your public behavior on GitHub, such as the projects you star — to determine your coding interests, and we recommend similar projects. These recommendations are automated decisions, but they have no legal impact on your rights.\r\n\r\nWe collect Technical Information to better understand how our website visitors use GitHub, and to monitor and protect the security of the website.\r\n\r\nWe collect personal information from third parties for the purposes for which it was authorized to be collected. For example, you may authorize GitHub to contact you for marketing purposes via a third party's platform. If we need to use your personal information for other purposes, we will ask your permission first.\r\n\r\nWe use your User Personal Information and Technical Information for internal purposes, such as to maintain logs for security reasons, for training purposes, and for legal documentation and compliance.\r\n\r\nWe limit our use of your User Personal Information to the purposes listed in this Privacy Statement. If we need to use your User Personal Information for other purposes, we will ask your permission first. You can always see what information we have, how we're using it, and what permissions you have given us in your user profile."
]

[rubric.noncritical-purposes]
value = "opt-out-all"
citations = [
  "Some browsers have incorporated \"Do Not Track\" (DNT) features that can send a signal to the websites you visit indicating you do not wish to be tracked. GitHub responds to browser DNT signals and follows the W3C standard for responding to DNT signals. If you have not enabled DNT on a browser that supports it, cookies on some parts of our website will track your online browsing activity on other online services over time, though we do not permit third parties other than our analytics and service providers to track GitHub users' activity over time on GitHub."
]
notes = [
  "GitHub has few (if not none) non-critical uses of data apart from analytics."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "GitHub may disclose personally-identifying information or other information we collect about you to law enforcement in response to a valid subpoena, court order, warrant, or similar government order, or when we believe in good faith that disclosure is reasonably necessary to protect our property or rights, or those of third parties or the public at large."
]

[rubric.list-collected]
value = "generally"
citations = [
  "\"User Personal Information\" is any personal information about one of our users which could, alone or together with other information, personally identify them. Information such as a user name and password, an email address, a real name, and a photograph are examples of “User Personal Information.” User Personal Information includes Personal Data as defined in the General Data Protection Regulation.\r\n\r\n\"Technical Information\" may include information we collect from website browsers, such as web server logs, or other log information, such as User session or activity logs. Technical Information may be connected to User Personal Information such as a username or an email address, or to other potentially personally-identifying information like Internet Protocol (IP) addresses.\r\n\r\nIf you create an account, we require some basic information at the time of account creation. You will create your own user name and password, and we will ask you for a valid email address. You also have the option to give us more information if you want to, and this may include \"User Personal Information.\"\r\n\r\nIf you're just browsing the website, we collect the same basic information that most websites collect. We use common internet technologies, such as cookies and web server logs, to collect Technical Information. This is stuff we collect from everybody, whether they have an account or not.\r\n\r\nThe information we collect about all visitors to our website includes the visitor’s browser type, language preference, referring site, additional websites requested, and the date and time of each visitor request. We also collect potentially personally-identifying information like Internet Protocol (IP) addresses."
]

[rubric.revision-notify]
value = "yes"
citations = [
  "We will provide notification to Users of material changes to this Privacy Statement through our Website at least 30 days prior to the change taking effect by posting a notice on our home page or sending email to the primary email address specified in your GitHub account."
]
