name = "hCaptcha"
description = "hCaptcha is a captcha service that pays the site owners."
slug = "hcaptcha"
hostnames = [ "hcaptcha.com" ]
sources = [ "https://www.hcaptcha.com/privacy" ]
contributors = [ "doamatto" ]

[rubric.behavioral-marketing]
value = "yes"
citations = [
  "We generally use Cookies for the following purposes:\n[...]\nTo serve you with interest-based or targeted advertising."
]

[rubric.security]
value = "somewhat"
citations = [
  "We implement appropriate technical and organizational measures to protect the information we collect and store. Unfortunately, no security measures are 100% foolproof, and as such no network or system (including ours) can be guaranteed to be 100% secure against destruction, loss, alteration, unauthorized disclosure of, or access to information we collect and store. If you believe your information may not be secure for any reason, please contact us immediately at support@hcaptcha.com."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "As discussed above, we (and our third party vendors) collect Analytics Information in part through the use of cookies, web beacons, and other tracking technologies. In some instance, we work with third party vendors to employ cookies for the purposes of collecting Analytics Information.\n\nWe use Sentry to collect debugging data when a user experiences an error. For information on how Sentry collects and processes data, please click here. We have executed a Data Processing Agreement (\"DPA\") with Sentry.\n\nWe use Cloudflare to optimize our web traffic. For information on how Cloudflare collects and processes data, please click here. We have executed a DPA with Cloudflare.\n\nWe use Customer.io for programmatic notifications to users. For information on how Customer.io collects and processes data, please click here. We have executed a DPA with Customer.io.\n\nWe previously used Google Analytics to collect Analytics Information. For information on how Google Analytics collects and processes data, please click here. We have executed a DPA with Google.\n\nWe use Honeycomb.io for analysis of our systems. For information on how Honeycomb.io collects and processes data, please click here. Honeycomb.io has certified under the EU-US Privacy Shield framework and complies with GDPR data protection requirements.\n\nIf you would prefer not to block the use of cookies or other tracking technologies, please see \"Managing Your Information,\" below. Please note that doing so may negatively impact your experience using the Site or Service, as some features may not work properly."
]

[rubric.history]
value = "last-modified"
citations = [ "Last updated: May 07, 2020" ]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "You may access, correct, amend, or delete certain Personal Information you may have provided us through your User account (if you are a User). If you are unable to do so, or have any questions about Personal Information we have collected about you, or would like to entirely delete your account, please contact us at support@hcaptcha.com."
]

[rubric.data-breaches]
value = "no"
notes = [
  "This service is not required to notify you of data breaches"
]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "We share or disclose information in the following cases:\n\n- Upon direct request from a Visitor or User, or otherwise where specific consent was given.\n- With our customers and others interested in acquiring Labeled Data.\n- With vendors we engage to provide essential aspects of the Site and the Service, such as data storage and hosting, and only for those purposes.\n- With vendors to help us collect and use Analytics Information.\n- As necessary to comply with applicable law, including governmental requests, law enforcement requests, and otherwise to protect the rights, privacy, safety, or property of you, us, or others.\n- With others for any legitimate business purpose, provided the information is anonymized."
]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "We use the information we collect for the following purposes:\n\n- To provide a market for Labeled Data. Our Service enables high volume data labeling and human review for machine learning systems as a service to website owners and companies who need help getting their data labeled. To that end, we disclose Labeled Data to our customers interested in acquiring Labeled Data.\n- To administer User accounts and provide the Service. We use Personal Information in order to associate specific accounts with Users and to provide them the Service, to respond to requests or inquiries, to provide support or technical assistance, and to facilitate payments.\n- To improve to Site and the Service. We use Analytics Information to improve our existing and develop new services and offerings and to customize existing and future product offerings to the wants and needs of our Users.\n- To derive market insights. We use Analytics Information to analyze the market and conduct business analyses related to the Site and our Services, and for other research purposes.\n- To secure our services and systems. We use Analytics Information to secure our systems by identifying potential threats and vulnerabilities, and to otherwise protect the information we collect.\nFor any legitimate business purpose, provided that the information is anonymized."
]

[rubric.noncritical-purposes]
value = "no"
notes = [
  "There aren't any ways to opt-out of non-critical use of data."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "We share or disclose information in the following cases: [...] As necessary to comply with applicable law, including governmental requests, law enforcement requests, and otherwise to protect the rights, privacy, safety, or property of you, us, or others."
]

[rubric.list-collected]
value = "summarily"
citations = [
  "We collect information from individuals who interact with our Site and Services, including those who incorporate the Service into their website (\"Users\") and the end users who interact with the Service through the websites of our Users.\n\nWe collect the following categories of information:\n\n- Information that can be used to identify or contact an individual (\"Personal Information\"), such as name and email address. We collect Personal Information from our Users when they give it directly to us (for example, by filling in a form when signing up for an account).\n- Information collected automatically as a result of a Visitors or Users use of the Site or the Services (\"Analytics Information\"), such as IP addresses, browser type, Internet service provider, platform type, device type, operating system, date and time stamp of access, and other similar information. Some Analytics Information is collected on our behalf by third parties we engage for that purpose, and some Analytics Information is collected through a variety of tracking technologies, including cookies (see \"See Third Party Analytics and Tracking Technologies\", below).\n- Information collected as a result of individuals answering prompts through the Service (\"Labeled Data\"), such as image labeling data, text converted from audio files played to those individuals, answers to questions, and other prompts ge"
]

[rubric.revision-notify]
value = "yes"
citations = [
  "Any information that we collect is subject to the Privacy Policy in effect at the time such information is collected. We may, however, revise the Privacy Policy from time to time. If a revision is material, as determined solely by us, we will notify you, for example via email. The current version will always be posted to our Privacy Policy page.\n\nIf you have any questions about this Privacy Policy, please contact us at support@hcaptcha.com."
]
