name = "ProtonMail"
description = "Secure email service with End-to-End Encryption based in Switzerland."
slug = "protonmail"
hostnames = [ "protonmail.com", "protonmail.ch" ]
sources = [ "https://protonmail.com/privacy-policy" ]
contributors = [ "Deivedux" ]

[rubric.behavioral-marketing]
value = "no"
citations = ["Such data will only be used to contact you with important notifications about ProtonMail, to send you information related to security, to send you an invitation link to create your ProtonMail account, to verify your ProtonMail account, or to send you password recovery links if you enable the option. We may also inform you about new Proton products in which you might have an interest. You are free, at any given time, to opt-out of those features through the account settings panel."]
notes = ["ProtonMail subscribes users to 4 individual mailing lists, that they can opt-out from at any time, and all emails are the same to everyone."]

[rubric.data-breaches]
value = "no"
notes = ["The policy does not specify a data breach protocol."]

[rubric.data-collection-reasoning]
value = "yes"
notes = ["ProtonMail includes an extensive list of data that it collects, and the reasons why."]

[rubric.data-deletion]
value = "yes-automated"
citations = ["When a ProtonMail account is closed, data is immediately deleted from production servers. [...] Deleted emails are also permanently deleted from production servers. Deleted data may be retained in our backups for up to 14 days."]

[rubric.history]
value = "last-modified"
notes = ["A \"Last modified\" date is present at the start of the policy."]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "We will only disclose the limited user data we possess if we are instructed to do so by a fully binding request coming from the competent Swiss authorities (legal obligation).",
  "ProtonMail may from time to time, contest requests if there is a public interest in doing so. In such situations, the Company will not comply with the request until all legal or other remedies have been exhausted. Therefore, not all requests described in our Transparency Report will lead to data disclosure."
]
notes = ["ProtonMail is willing to disclose just enough personal data that they think will help authorities investigate a criminal activity, given enough reasons to do so."]

[rubric.list-collected]
value = "exhaustively"
notes = ["ProtonMail includes an extensive list of data that it collects, and the reasons why."]

[rubric.noncritical-purposes]
value = "na"
notes = ["ProtonMail does not collect any non-critical personal data."]

[rubric.revision-notify]
value = "yes"
citations = ["ProtonMail reserves the right to periodically review and change this policy from time to time and we will notify users who have enabled the notification preference about changes to our Privacy Policy."]

[rubric.security]
value = "yes"
citations = ["All servers used in connection with the provisioning of the Service are located in Switzerland and wholly owned and operated by the Company. Only employees of the Company have physical or other access to the servers. Data is ALWAYS stored in encrypted format on our servers. Offline backups may be stored periodically, but these are also encrypted. We do not possess the ability to access any user encrypted message content on either the production servers or in the backups."]

[rubric.third-party-access]
value = "yes-unspecified-critical"
citations = ["The Company relies on third parties to process credit card, PayPal, and Bitcoin transactions so the Company necessarily must share payment information with third parties. Anonymous cash or Bitcoin payments and donations are accepted however. The legal basis of this processing is the necessity to the execution of the contract between you and us."]
notes = ["They don't explicitly list the actual third-parties involved."]

[rubric.third-party-collection]
value = "no"
notes = ["Their policy does not contain information regarding data collection from third-parties."]
