name = "Wells Fargo "
description = "Multinational financial service provider."
slug = "wells-fargo"
hostnames = [ "https://www.wellsfargo.com/" ]
sources = [
  "https://www.wellsfargo.com/privacy-security/privacy/online/"
]
contributors = [ "UnKnOwN" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  "We use cookies and information gathered through their use to make your experience with Wells Fargo and certain other sites richer and more personalized based on the products, services, or other interaction you have with us and other sites."
]
notes = [
  "Advertisers on the Wells Fargo do offer opt-out tools, however they can sometimes be hard to use."
]

[rubric.security]
value = "somewhat"
citations = [
  "The Personal Data will be safely stored in the databases of Wells Fargo. Appropriate measures are taken so that Personal Data can be kept accurate, and up-to-date, which will be in accordance with the applicable security requirements. In an effort to prevent the loss, misuse, unauthorized access, disclosure, alteration or destruction of Personal Data, Wells Fargo will take appropriate legal, organizational and technical measures to protect Personal Data. We will keep Personal Data no longer than necessary to fulfill the purposes outlined in this Notice and have implemented appropriate record retention policies. "
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "Other parties that may collect information about your web browsing behavior when you use our Site are generally limited to service providers who may only use any information collected to provide services and marketing for us and not to provide services or advertising for any other party."
]

[rubric.history]
value = "last-modified"
notes = [
  "The last modified date is available at the top of the policy."
]

[rubric.data-deletion]
value = "no"
notes = [
  "Nothing is mentioned about the data deletion in the privacy policy. "
]

[rubric.data-breaches]
value = "no"
citations = [
  "Nothing is mentioned about data breaches in the privacy policy."
]

[rubric.third-party-access]
value = "yes-unspecified"
notes = [
  "There is an explicit list of affiliated entities that Wells Fargo shares users' personal data, however, the company does not specify beneficiaries or service providers it shares personal data with."
]

[rubric.data-collection-reasoning]
value = "somewhat"
citations = [
  "[...] we use information for purposes as allowed by law such as: servicing; communicating with you; improving our Site, products, or services; legal compliance; risk control; information security; anti-fraud purposes; marketing or personalizing the presentation of our products and services to you; tracking website usage, such as number of hits, pages visited, and the length of user sessions in order to evaluate the usefulness of our sites; and using read-receipt notifications in our email communications."
]
notes = [
  "The explanation is very general and also \"such as\" phrase is used before the purposes listing, thus making the statement not absolute."
]

[rubric.noncritical-purposes]
value = "opt-out-some"
citations = [
  "If you receive an ad delivered on a third party site in part based on information gathered through the use of cookies, you may opt out of receiving such ads by clicking the displayed icon and following the instructions or by visiting http://www.aboutads.info/choices/."
]
notes = [
  "The policy allows opting-out of cookies receiving, but data company collects can still be used for non-critical purposes internally within Wells Fargo (for example, for marketing)."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "Subject to applicable law, the Wells Fargo Group may disclose Personal Data if required or permitted by applicable law or regulation, including laws and regulations of the United States and other countries, or in the good faith belief that such action is necessary to comply with a legal obligation or in response to a request from law enforcement or other public authorities wherever the Wells Fargo Group may do business [...] "
]

[rubric.list-collected]
value = "generally"
citations = [
  "Information that we may collect about you through online interaction includes information that you input, such as your name, address, email address, other contact information; data resulting from your activity, such as transaction information; and location information. We may also gather additional information, such as the type of device and browser you are using, the IP address of your device, information about your device’s operating system, and additional information associated with your device. We may also gather information collected through cookies, tags, and other technologies, as described further below."
]
notes = [
  "The categories of personal data are listed, however, there are many \"such as\" phrases which make statements non-absolute."
]

[rubric.revision-notify]
value = "no"
citations = [
  "If we make updates to this Policy, we will update the Policy with the changes and revise the “date of most recent update” posted at the top of this Policy. Any updates to the Policy become effective when we post the updates on the Site. Your use of the Site following the update to the Policy means that you accept the updated Policy."
]
