name = "Wire"
description = "Wire is a cross-platform encrypted communication and collaboration service created by Wire Swiss."
slug = "wire"
hostnames = [ "wire.com"]
sources = [ "https://wire.com/en/legal/#privacy" ]
contributors = [ "erotavlas" ]

[rubric.behavioral-marketing]
value = "no"
citations = [
  "\"There are no ads. Therefore your personal data or the content of your conversations is never sold or rented to anyone, it will never be used for any third-party advertising.\" \r\n\r\n \"Your data is also not used for targeted ads, or any other kind of profiling.\""
]

[rubric.security]
value = "yes-independent-audits"
citations = [
  "\"All conversation content is encrypted with strong encryption on the sender's device and is only decrypted on the recipient's device (also known as end-to-end encryption). Wire doesn't hold the decryption keys, and our software contains no backdoor. Your conversations are yours - Wire has no access to them. In addition, Wire also uses transport encryption to encrypt metadata.\" \r\n\r\n \"Your privacy is very important to us. [Find out more](https://wire.com/en/security/). All communication through Wire is secured with end-to-end encryption â€” messages, conference calls, files. Wire is the most extensively publicly audited collaboration and communication software on the market.\""
]

[rubric.third-party-collection]
value = "no"
notes = [
    "Wire does not collect any data from third parties."]

[rubric.history]
value = "last-modified"
citations = [
    "\"This Privacy Policy may change from time to time. We will make the revised Privacy Policy available through the Apps and post a revised version of this Privacy Policy on the website. Please check the Privacy Policy regularly to be informed of any changes.\""
]

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "\"We store your profile information only for the duration of your account usage. If you delete your account, we will delete your profile information immediately. You can change or delete your profile data at any time.\" \r\n\r\n \"If you send us an inquiry about our products as an interested party, we collect the information you provide, such as your name, e-mail address or other contact information you provide us with. We delete your data after the processing of your inquiry is completed.\" \r\n\r\n \"When you contact Wire Customer Service for a support request, we process the personal information you provide in the support request for the purpose of processing your support request. We delete your personal data processed for the processing of the support request after the processing of your request has been completed.\" \r\n\r\n \"if we collect and store data for tax reasons, we delete this data within 6 months after our contract with you is terminated or after the expiry of any existing legal obligation to retain data.\""
]
  
[rubric.data-breaches]
value = "no"
notes = [ 
  "The policy does not specify a data breach protocol."]

[rubric.third-party-access]
value = "yes-specified-critical"
citations = [
    "\"Wire undertakes to select only third-party providers for the provision of Wire services in the EU and/or Switzerland.\" \r\n\r\n \"Wire will disclose personal data to third parties only if and to the extent necessary to provide the third party service (e.g., to respond to a support request), if required by law or legal process, or if necessary to enforce the Terms of Use and/or protect Wire's rights.\" \r\n\r\n \"In addition, to the extent permitted by data protection law, Wire may disclose your personal data to third parties if we (or our affiliates) are acquired by that third party with any of our assets or voting securities (or those of our affiliates) or if we are otherwise involved in a transaction with similar financial effect. In such a situation, we will use reasonable efforts to require the third party to process your data in accordance with this Privacy Policy in relation to your personal data.\" \r\n\r\n \"If you use third-party services such as YouTube, Spotify, Giphy etc. via the Wire application, all data that you share with these services is subject to their privacy policies.\""
]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "\"We are transparent about the data we collect and what we do and don't do with it. Anonymized (hashed) contact information from address books will only be used to connect users on Wire.\""
]

[rubric.noncritical-purposes]
value = "na"
citations = [
  "\"There are no ads. Therefore your personal data or the content of your conversations is never sold or rented to anyone, it will never be used for any third-party advertising.\" \r\n\r\n \"Your data is also not used for targeted ads, or any other kind of profiling.\" \r\n\r\n \"We are transparent about the data we collect and what we do and don't do with it.\""
]

[rubric.law-enforcement]
value = "strict"
citations = [
  "\"Wire follows European privacy laws. Wire will not disclose your data to public authorities unless Wire is obliged to do so under Swiss law.\" \r\n\r\n \"The Wire [Transparency Report](https://wire-docs.wire.com/download/Wire%2BTransparency%2BReport.pdf) contains details about how often authorities request user data from Wire Swiss GmbH.\""
]

[rubric.list-collected]
value = "exhaustively"
citations = [
  "\"We are transparent about the data we collect and what we do and don't do with it.\" \"When you create an account with Wire, we ask you to provide a name and a mobile phone number or email address (\"Profile Information\"). The Profile Information you provide will be used for the purpose of providing Wire services and may be displayed to other Wire users when they search for you or connect to you through Wire services. If you have registered with a phone number, this information will not be displayed to other Wire users. If you registered with an email address, your email address may be visible to other users when using Wire Pro, depending on your preferences.\" \r\n\r\n \"If you create a Team Admin account or Team Member account with Wire, we may ask you for additional information for billing purposes and may share that information with a billing provider (\"Data relevant to payment\"). In order to make purchases through Wire services using a Team Admin account, Team Admins must provide a payment method and may be required to provide additional information such as billing address, phone number, email address, and zip code if required for tax purposes or to complete billing. In addition, other types of information related to the specific transaction may be collected, such as transaction amount and duration.\" \r\n\r\n \"You are free to give Wire services access to your address book contacts. This is for the purpose of communicating with other users of Wire services. In this case, only hashed phone numbers are processed volatilely. The rest of your address book content is never uploaded to our servers.\" \r\n\r\n \"If you send us an inquiry about our products as an interested party, we collect the information you provide, such as your name, e-mail address or other contact information you provide us with. If you have provided an e-mail address, Wire may send you e-mails to inform you of important changes (e.g. to confirm your e-mail address or to inform you that a new device has been added to your account).\" \r\n\r\n \"If you have given us your consent for the purpose of receiving our newsletter with information about Wire's offers and products by e-mail, Wire will process your e-mail address and name to send you the newsletter. You can unsubscribe from the newsletter at any time.\" \r\n\r\n \"When you contact Wire Customer Service for a support request, we process the personal information you provide in the support request for the purpose of processing your support request.\""
]

notes = [
  "\"Wire stores additional technical data (such as the type of device through which you authorized the Wire application) to be able to route data between user devices. The Wire service is designed to keep additional technical data to the minimum required to operate the service. More information about additional data can be found in the [Privacy Whitepaper](https://wire-docs.wire.com/download/Wire+Privacy+Whitepaper.pdf) and the [Security Whitepaper](https://wire-docs.wire.com/download/Wire+Security+Whitepaper.pdf).\" \r\n\r\n \"When you use Wire services, we may collect technical data, so-called \"log files\", with each access. Log files are kept for a maximum of 72 hours, and only to facilitate troubleshooting, improve the service and prevent misuse.\""]

[rubric.revision-notify]
value = "yes"
citations = [
  "\"This Privacy Policy may change from time to time. We will make the revised Privacy Policy available through the Apps and post a revised version of this Privacy Policy on the website. Please check the Privacy Policy regularly to be informed of any changes.\""
]
