name = "Yahoo!"
description = "Yahoo! is an American technology company owned by Verizon that provides a search engine and email."
slug = "yahoo"
hostnames = [ "yahoo.com" ]
sources = [ "https://policies.yahoo.com/xa/en/yahoo/privacy/index.htm" ]
icon = "yahoo.png"
updates = [ ]
contributors = [ "ibarakaiev" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  "\"Yahoo uses information for the following general purposes: to customize the advertising and content you see, fulfill your requests for products and services, improve our services, contact you, conduct research, and provide anonymous reporting for internal and external clients.\""
]

[rubric.security]
value = "yes"
citations = [
  "\"We limit access to personal information about you to employees who we believe reasonably need to come into contact with that information to provide products or services to you or in order to do their jobs.\r\n\r\nWe have physical, electronic, and procedural safeguards that comply with federal regulations to protect personal information about you.\r\n\r\nTo learn more about security, including the security steps we have taken and security steps you can take, please read (Security at Yahoo)[https://policies.yahoo.com/xa/en/yahoo/privacy/topics/security/index.htm].\""
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "\"Yahoo may combine information about you that we have with information we obtain from business partners or other companies.\""
]

[rubric.history]
value = "last-modified"
citations = [ "\"Last updated: 13 June 2017\"" ]

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "\"You can delete your Yahoo account by visiting our Account Deletion page. Please click here to read about information that might possibly remain in our archived records after your account has been deleted.\"\r\n\r\n\"You can edit your Yahoo Account Information, including your marketing preferences, at any time. You can also modify information you have provided to Yahoo through the Yahoo products or services you may use.\""
]

[rubric.data-breaches]
value = "no"
notes = [
  "No part of the policy mentions data breach disclosure protocol."
]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "\"We provide the information to trusted partners who work on behalf of or with Yahoo under confidentiality agreements. These companies may use your personal information to help Yahoo communicate with you about offers from Yahoo and our marketing partners. However, these companies do not have any independent right to share this information.\""
]

[rubric.data-collection-reasoning]
value = "no"
citations = [
  "\"Yahoo uses information for the following general purposes: to customize the advertising and content you see, fulfill your requests for products and services, improve our services, contact you, conduct research, and provide anonymous reporting for internal and external clients.\""
]

[rubric.noncritical-purposes]
value = "opt-out-some"
citations = [
  "\"You can edit your Yahoo Account Information, including your marketing preferences, at any time. You can also modify information you have provided to Yahoo through the Yahoo products or services you may use.\""
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "\"We respond to subpoenas, court orders, or legal process (such as law enforcement requests), or to establish or exercise our legal rights or defend against legal claims.\""
]

[rubric.list-collected]
value = "summarily"
citations = [
  "\"Yahoo collects personal information when you register with Yahoo, when you use Yahoo products or services, when you visit Yahoo pages or the pages of certain Yahoo partners, and when you enter promotions or sweepstakes. Yahoo may combine information about you that we have with information we obtain from business partners or other companies.\r\n\r\nWhen you register we ask for information such as your name, email address, birth date, gender, ZIP code, occupation, industry, and personal interests. For some financial products and services we might also ask for your address, Social Security number, and information about your assets. When you register with Yahoo and sign in to our services, you are not anonymous to us.\r\n\r\nYahoo collects information about your transactions with us and with some of our business partners, including information about your use of financial products and services that we offer.\r\n\r\nYahoo automatically receives and records information from your computer and browser, including your IP address, Yahoo cookie information, software and hardware attributes, and the page you request.\r\n\r\nYahoo uses information for the following general purposes: to customize the advertising and content you see, fulfill your requests for products and services, improve our services, contact you, conduct research, and provide anonymous reporting for internal and external clients.\""
]

[rubric.revision-notify]
value = "yes"
citations = [
  "\"Yahoo may update this policy. We will notify you about significant changes in the way we treat personal information by sending a notice to the primary email address specified in your Yahoo account or by placing a prominent notice on our site.\""
]
